name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu_latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: install dependencies
              run: npm ci
            - name: run test
              run: npm test  

                  
